### ISSUE TITLE
Robot

### ISSUE THREAD

**Issue by RobTF9** [bristol-tech-fair/btf-frontend#21]
Add the robot illustration component from Figma.

<img width="198" alt="Screenshot 2021-01-09 at 10 02 28" src="https://user-images.githubusercontent.com/35739573/104088885-d09a2380-5261-11eb-9fd6-39ae55bafafe.png">

View the design [here](https://www.figma.com/file/gGwSe7ilZCUmAIaJyUc4iY/Bristol-Tech-Fair-Design-System?node-id=544%3A3363).

**Comment by EdFildes** [comment]
@admtomas Do you need a hand with this? Happy to help out if needed.

**Comment by admtomas** [comment]
yes, thx have a look at the code and the way it can be improved or redesigned. And we need to match it with new design Rob just posted. Same code could be shared for other 2 Robot Images with some tweaks to dimensions

**Comment by EdFildes** [comment]
@admtomas The implementation looks pretty solid to me, I have a few questions about it though:

Firstly, I can see that you're passing "path" down as props. This suggests that we will be reusing this Robot component for other positions of the robot, such as the one where its lying down. Is this correct? Otherwise we should just hard code path. 

Also how did you obtain the base64 encoded png that is found in path.js? When I download the svg from figma it just gives me the clip path in place of that?
